# Generated by Django 2.1.7 on 2021-10-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchasedetails',
            table='purchase_details',
        ),
    ]
