# Generated by Django 2.1.7 on 2021-10-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_auto_20211015_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetails',
            name='purchased_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
