# Generated by Django 2.1.7 on 2021-10-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_auto_20211028_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='mobile_no',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
    ]
