# Generated by Django 3.2.9 on 2021-11-09 04:36

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_auto_20211029_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillDetails',
            fields=[
                ('bill_no', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('bill_data', jsonfield.fields.JSONField()),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'bill_details',
            },
        ),
    ]
