# Generated by Django 2.1.7 on 2021-10-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedetails',
            name='medicine_name',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True, unique=True),
        ),
    ]
