# Generated by Django 2.1.7 on 2021-11-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_auto_20211017_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusDetails',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'status_details',
            },
        ),
    ]
